// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package energy

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// BaselinePage is paging.Page[Baseline].
type BaselinePage struct {
	Items           []Baseline `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Baseline](BaselinePage{})

// FactorPage is paging.Page[Factor].
type FactorPage struct {
	Items           []Factor `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Factor](FactorPage{})

// RecordPage is paging.Page[Record].
type RecordPage struct {
	Items           []Record `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Record](RecordPage{})

// ReportPage is paging.Page[Report].
type ReportPage struct {
	Items           []Report `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Report](ReportPage{})
