// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Documentation stubs of the further REST routes of this package's operations (IR222): swag documents one
// route per function, so the update route of a save and the verb routes of a transition are annotated here; the
// handlers carry the first route of each operation.

package energy

import (
	"github.com/pradita/ac-project/service/api/internal/ops"
	"github.com/pradita/ac-project/service/api/internal/platform/apperr"
)

var (
	_ ops.Envelope
	_ apperr.DomainError
	_ = swaggerBaselinesSaveUpdate
	_ = swaggerFactorsSaveUpdate
	_ = swaggerMrvSaveDraftUpdate
)

// swaggerBaselinesSaveUpdate documents a further REST route.
//
//	@Summary		baselines.save (write) — update
//	@ID				baselines.save.update
//	@Description	Authorization: admin:energy.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; SR29 Repository computes measured quality; fixed is modeled
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A13
//	@Tags			baselines
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target baselines, read baselines.list)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		BaselineInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Baseline}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/baselines/{id} [put]
func swaggerBaselinesSaveUpdate() {}

// swaggerFactorsSaveUpdate documents a further REST route.
//
//	@Summary		factors.save (write) — update
//	@ID				factors.save.update
//	@Description	Authorization: admin:mrv.factors
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A14
//	@Tags			factors
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string		true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer		true	"id present: required (target factors, read factors.list)"
//	@Param			id					path		string		true	"input field id"
//	@Param			request				body		FactorInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Factor}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/factors/{id} [put]
func swaggerFactorsSaveUpdate() {}

// swaggerMrvSaveDraftUpdate documents a further REST route.
//
//	@Summary		mrv.saveDraft (write) — update
//	@ID				mrv.saveDraft.update
//	@Description	Authorization: admin:mrv.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A14
//	@Tags			mrv
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string		true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer		true	"id present: required (target mrv, read mrv.get)"
//	@Param			id					path		string		true	"input field id"
//	@Param			request				body		SaveInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Report}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/mrv/{id} [put]
func swaggerMrvSaveDraftUpdate() {}
