// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package maintenance

import (
	"github.com/pradita/ac-project/service/api/internal/modules/identity"
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// CapacityPage is paging.Page[Capacity].
type CapacityPage struct {
	Items           []Capacity `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Capacity](CapacityPage{})

// CertificatePage is paging.Page[Certificate].
type CertificatePage struct {
	Items           []Certificate `json:"items"`
	NextCursor      *string       `json:"nextCursor"`
	Total           int           `json:"total"`
	SnapshotVersion int           `json:"snapshotVersion"`
}

var _ = paging.Page[Certificate](CertificatePage{})

// EventPage is paging.Page[Event].
type EventPage struct {
	Items           []Event `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Event](EventPage{})

// FilterStatusPage is paging.Page[FilterStatus].
type FilterStatusPage struct {
	Items           []FilterStatus `json:"items"`
	NextCursor      *string        `json:"nextCursor"`
	Total           int            `json:"total"`
	SnapshotVersion int            `json:"snapshotVersion"`
}

var _ = paging.Page[FilterStatus](FilterStatusPage{})

// MemberPage is paging.Page[identity.Member].
type MemberPage struct {
	Items           []identity.Member `json:"items"`
	NextCursor      *string           `json:"nextCursor"`
	Total           int               `json:"total"`
	SnapshotVersion int               `json:"snapshotVersion"`
}

var _ = paging.Page[identity.Member](MemberPage{})

// PartItemPage is paging.Page[PartItem].
type PartItemPage struct {
	Items           []PartItem `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[PartItem](PartItemPage{})

// PlanPage is paging.Page[Plan].
type PlanPage struct {
	Items           []Plan  `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Plan](PlanPage{})

// ProfilePage is paging.Page[Profile].
type ProfilePage struct {
	Items           []Profile `json:"items"`
	NextCursor      *string   `json:"nextCursor"`
	Total           int       `json:"total"`
	SnapshotVersion int       `json:"snapshotVersion"`
}

var _ = paging.Page[Profile](ProfilePage{})

// RateCardPage is paging.Page[RateCard].
type RateCardPage struct {
	Items           []RateCard `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[RateCard](RateCardPage{})

// anyPage is paging.Page[any].
type anyPage struct {
	Items           []any   `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[any](anyPage{})
