// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Documentation stubs of the further REST routes of this package's operations (IR222): swag documents one
// route per function, so the update route of a save and the verb routes of a transition are annotated here; the
// handlers carry the first route of each operation.

package maintenance

import (
	"github.com/pradita/ac-project/service/api/internal/ops"
	"github.com/pradita/ac-project/service/api/internal/platform/apperr"
)

var (
	_ ops.Envelope
	_ apperr.DomainError
	_ = swaggerContractorsSaveUpdate
	_ = swaggerPlansSaveUpdate
)

// swaggerContractorsSaveUpdate documents a further REST route.
//
//	@Summary		contractors.save (write) — update
//	@ID				contractors.save.update
//	@Description	Authorization: admin:job.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR111 organization kind=contractor; service areas at least one
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A21
//	@Tags			contractors
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target contractor, read contractors.list)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		ProfileInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Profile}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/contractors/{id} [put]
func swaggerContractorsSaveUpdate() {}

// swaggerPlansSaveUpdate documents a further REST route.
//
//	@Summary		plans.save (write) — update
//	@ID				plans.save.update
//	@Description	Authorization: admin:job.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A06
//	@Tags			plans
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target plans, read plans.get)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		PlanSaveInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Plan}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/plans/{id} [put]
func swaggerPlansSaveUpdate() {}
