// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package audit

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// ViewPage is paging.Page[View].
type ViewPage struct {
	Items           []View  `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[View](ViewPage{})
