/** 0.22.0 / 1A frontend specification only; no implementation or HTTP contract.
 * Numeric/string constraints and policy guards: deterministic-contracts.md and strict-review-contracts.md and review-resolution-contracts.md (all sections).
 * Optional fields mean omitted input; output absence is explicit null.
 */
export type ID = string;
export type Instant = string; // ISO UTC, millisecond precision
export type Role = 'client'|'contractor'|'technician'|'admin';
export type Locale = 'en'|'ms';
export type Currency = 'MYR'|'USD';
export type ErrorCode = 'VALIDATION'|'UNAUTHENTICATED'|'FORBIDDEN'|'NOT_FOUND'|'CONFLICT'|'OFFLINE'|'TIMEOUT'|'RATE_LIMITED'|'UNAVAILABLE';
export type DomainError = {code:ErrorCode;messageKey:string;fieldErrors:Record<string,string>;correlationId:ID;retryAfterSeconds:number|null};
export type Context = {tenantId:ID;membershipId:ID;scopeVersion:number};
export type WriteOptions = {idempotencyKey:ID;expectedVersion?:number};
export type Entity = {id:ID;tenantId:ID;version:number;createdAt:Instant;updatedAt:Instant};
export type Meta = {correlationId:ID;snapshotAt:Instant;eventCursor:number};
export type ServiceResult<T> = {data:T;meta:Meta};
export type Page<T> = {items:T[];nextCursor:string|null;total:number;snapshotVersion:number};
export type Range = {from:Instant;to:Instant};
export type Money = {amountMinor:number;currency:Currency};
/** IR107: 38 values = Read/Write per resource + independent actions. Write implies Read. */
export type Permission = 'dashboard.read'|'asset.read'|'asset.write'|'identity.read'|'identity.write'|'device.read'|'device.write'|'device.maintain'|'control.execute'|'control.diagnose'|'alert.read'|'alert.resolve'|'alert.policy.read'|'alert.policy.write'|'job.read'|'job.write'|'contract.read'|'contract.write'|'billing.read'|'billing.write'|'billing.payment'|'restriction.read'|'restriction.write'|'restriction.override'|'automation.policy.read'|'automation.policy.write'|'energy.read'|'energy.write'|'mrv.read'|'mrv.write'|'mrv.review'|'mrv.factors'|'offset.read'|'offset.write'|'audit.read'|'partner.accept'|'partner.assign'|'partner.review';
export type Session = Context & {userId:ID;role:Role;clientRole:ClientRole|null;permissions:Permission[];generation:number;viewEpoch:number;issuedAt:Instant;expiresAt:Instant};
export type Preferences = {locale:Locale;timezone:string;currency:'MYR';monthlyReportEmail:boolean;twoFactorEnabled:boolean};
export type User = {id:ID;displayName:string};
export type Membership = Entity & {userId:ID;displayName:string;organizationId:ID;role:Role;employment:'internal'|'external'|null;permissions:Permission[];scopes:ScopeRef[];scopeVersion:number;qualifications:QualificationGrant[];validFrom:Instant;validUntil:Instant|null;clientRole:ClientRole|null};
export type Organization = Entity & {name:string;kind:'customer'|'contractor'|'operator';status:'active'|'inactive'};
export type Customer = Entity & {name:string;status:'active'|'inactive';organizationId:ID;serviceProfile:'rto'|'general'|'energy'|'environment'};
export type Property = Entity & {customerOrgId:ID;kind:'home'|'office';name:string;address:string|null;accessInstructions:string|null;archived:boolean};
export type Space = Entity & {propertyId:ID;parentSpaceId:ID|null;kind:'area'|'floor'|'room'|'space';name:string;archived:boolean};
export type Metric = 'temperature'|'humidity'|'co2'|'pm25'|'power'|'vibration'|'refrigerant_pressure'|'compressor_cycles'|'airflow_drop'|'heartbeat_gap';
export type UnitSymbol = '°C'|'%'|'ppm'|'µg/m³'|'kW'|'mm/s'|'kPa'|'cycles/h'|'min';
export type Quality = 'valid'|'missing'|'stale'|'suspect';
export type Measurement = Entity & {boundaryId:EnergyBoundaryId|null;qualityReason:MeasurementIssue|null;rawUnit:string|null;unitId:ID;sensorId:ID;metric:Metric;value:number|null;unit:UnitSymbol;observedAt:Instant;receivedAt:Instant;origin:'measured'|'estimated'|'inspection';quality:Quality;isDemo:true;sequence:number;eventId:ID};
export type Sensor = {boundaryId:EnergyBoundaryId|null;id:ID;deviceId:ID;metric:Metric;unit:UnitSymbol;staleAfterSeconds:number;calibratedAt:Instant|null};
export type Capability = Entity & {manufacturer:string;model:string;control:boolean;modeControl:boolean;fanControl:boolean;temperature:{min:number;max:number;step:number}|null;modes:Mode[];fanLevels:Fan[];ventilation:boolean;ventilationLevels:Fan[];sensors:Omit<Sensor,'id'|'deviceId'|'calibratedAt'>[];firmwareCandidates:string[]};
export type Mode = 'cool'|'dry'|'fan';
export type Fan = 'low'|'mid'|'high';
export type Connection = 'online'|'offline'|'unknown'|'connecting'|'error';
export type ObservedState = {power:boolean|null;celsius:number|null;mode:Mode|null;fanLevel:Fan|null;observedAt:Instant|null};
export type RestrictionPolicy = {kind:'temperature_limit';minimumCoolingSetpoint:number}|{kind:'power_off'};
export type ObservedRestriction = {restrictionId:ID;rulesVersion:ID;policy:RestrictionPolicy;observedAt:Instant}|null;
export type ACUnit = Entity & {customerOrgId:ID;propertyId:ID;spaceId:ID|null;displayName:string;modelId:ID;type:'split';installedAt:Instant|null;serviceScope:('indoor'|'outdoor'|'electrical')[];warrantyEndsAt:Instant|null;alertPolicyIds:ID[];archived:boolean;capabilityVersion:number;connection:Connection;observedState:ObservedState;observedRestriction:ObservedRestriction;lastSeenAt:Instant|null};
/** IR213: latestMeasurements = per metric the latest reading at or before now (observedAt desc, sequence desc, id asc), read-time quality (stale past the sensor's staleAfterSeconds); [] without readings. */
export type UnitSummary = ACUnit & {effectivePowerState:EffectivePowerState;latestMeasurements:Measurement[];activeAlertCount:number};
export type UnitDetail = UnitSummary & {capabilities:Capability;effectiveControlPolicy:EffectiveControlPolicy;controlAvailability:ControlAvailability;components:ComponentKey[];pendingCommands:Command[];pendingCommandIds:ID[];location:{pathLabels:string[];address:string|null;accessInstructions:string|null}};
export type UnitAction = {kind:'set_power';power:boolean}|{kind:'set_temperature';celsius:number}|{kind:'set_mode';mode:Mode}|{kind:'set_fan';fanLevel:Fan}|{kind:'ventilate';level:Fan};
export type RestrictionAction = {kind:'apply_restriction';restrictionId:ID;rulesVersion:ID;policy:RestrictionPolicy}|{kind:'remove_restriction';restrictionId:ID;rulesVersion:ID};
export type Command = Entity & {unitId:ID;actorMembershipId:ID;action:UnitAction|RestrictionAction;diagnosticRunId:ID|null;jobId:ID|null;reason:string|null;status:'requested'|'sent'|'acknowledged'|'failed'|'expired'|'cancelled';delivery:'not_sent'|'sent';requestedAt:Instant;sentAt:Instant|null;acknowledgedAt:Instant|null;expiresAt:Instant;failureCode:ErrorCode|null;correlationId:ID;source:'ui'|'voice'|'automation'|'restriction'|'diagnostic'|'group'};
export type DiagnosticRun = Entity & {jobId:ID;unitId:ID;actorMembershipId:ID;startAction:UnitAction;endAction:UnitAction;durationMinutes:number;reason:string;state:'awaiting_start'|'running'|'end_requested'|'completed'|'start_failed'|'end_failed'|'end_blocked';startCommandId:ID;endCommandId:ID|null;startedAt:Instant|null;endAt:Instant|null;failureCode:ErrorCode|null};
export type Severity = 'critical'|'warning'|'normal';
export type Alert = Entity & {unitId:ID;policyId:ID|null;type:'sensor'|'quality'|'maintenance'|'tamper'|'reconciliation_required';severity:Severity;status:'open'|'acknowledged'|'resolved';causeCode:'window_open'|'insulation_loss'|'unknown';evidenceKind:'demo_observation'|'inferred'|'inspection';evidenceText:string;observedAt:Instant;evidenceIds:ID[];detectedAt:Instant;acknowledgedAt:Instant|null;resolvedAt:Instant|null;resolutionReason:string|null;previousAlertId:ID|null;deliveryFailures:DeliveryFailure[]};
export type Slot = {startAt:Instant;endAt:Instant};
/** IR113: where a job came from. client_request = created by a client (or by HQ on a client's behalf) with preferred times; periodic_plan = generated from a MaintenancePlan. */
export type JobOrigin = 'client_request'|'periodic_plan';
export type SlotHold = {kind:'internal';membershipId:ID}|{kind:'contractor';contractorOrgId:ID;technicianMembershipId:ID|null};
/** IR113: a time outside the client's preferred times; booked only after the client accepts it. */
export type SlotProposal = {id:ID;source:'hq'|'contractor';slot:Slot;hold:SlotHold;message:string;replyBy:Instant;status:'pending'|'accepted'|'declined'|'withdrawn'|'expired';decidedAt:Instant|null;declineReason:'not_home'|'too_late'|'other'|null;declineComment:string|null};
export type PartnerSlotProposal = {id:ID;offerId:ID;slot:Slot;technicianMembershipId:ID;reason:string;sentAt:Instant;status:'pending'|'sent_to_client'|'kept'|'approved'|'declined'|'withdrawn'};
/** IR113: UI status; time_proposed = slotProposal.status pending (job stays requested or offered). */
export type JobDisplayStatus = JobStatus|'time_proposed';
export type JobStatus = 'requested'|'offered'|'accepted'|'assigned'|'in_progress'|'submitted'|'completed'|'rework_requested'|'cancelled'|'on_hold';
/** DEC-18: display ranking only, not a transition sequence. */
export const JOB_STATUS_ORDER = ['requested','offered','accepted','assigned','in_progress','on_hold','submitted','rework_requested','completed','cancelled'] as const satisfies readonly JobStatus[];
export type Offer = Entity & {jobId:ID;contractorOrgId:ID;termsVersion:ID;visitSlot:Slot;offeredAt:Instant;offerExpiresAt:Instant;accessValidFrom:Instant;accessValidUntil:Instant;decision:'accept'|'decline'|null;decidedBy:ID|null;decidedAt:Instant|null;declineReason:string|null};
export type Assignment = Entity & {jobId:ID;technicianMembershipId:ID;validFrom:Instant;validUntil:Instant;scheduledStart:Instant;scheduledEnd:Instant;status:'active'|'revoked';reason:string|null;acknowledgement:'pending'|'accepted'|'cant_make';acknowledgedAt:Instant|null;cantMakeReason:string|null;alternativeSlot:Slot|null};
export type ReportRef = {reportId:ID;reportVersion:number};
export type CostLine = Money & {kind:'estimate'|'actual';description:string;visibility:'internal'|'customer'};
export type MaintenanceJob = Entity & {planId:ID|null;occurrenceAt:Instant|null;unitId:ID;alertIds:ID[];type:'periodic'|'reactive'|'preventive';status:JobStatus;symptom:string;contactWindow:string|null;requestedSlot:Slot;origin:JobOrigin;preferredSlots:Slot[];preferenceRound:number;slotProposal:SlotProposal|null;partnerSlotProposal:PartnerSlotProposal|null;scheduledSlot:Slot|null;dueAt:Instant;startedAt:Instant|null;completedAt:Instant|null;contractorOrgId:ID|null;assignmentId:ID|null;draftReportRef:ReportRef|null;reportRefs:ReportRef[];costs:CostLine[];followUpOfJobId:ID|null;followUpClass:'pending'|'rework'|'new_request'|null;timeOnSite:TimeOnSite|null;rating:JobRating|null;customerConfirmedAt:Instant|null;warrantyClaims:WarrantyClaim[]};
export type JobSummary = Pick<MaintenanceJob,'id'|'version'|'unitId'|'type'|'status'|'dueAt'|'requestedSlot'|'scheduledSlot'|'assignmentId'|'origin'|'preferredSlots'> & {projection:'summary';severity:Severity;isDemo:true;displayStatus:JobDisplayStatus;assignmentAcknowledgement:Assignment['acknowledgement']|null};
export type JobOfferSummary = {projection:'offer';status:'offered'|'accepted';severity:null;jobId:ID;jobVersion:number;offerId:ID;type:MaintenanceJob['type'];siteAddress:string|null;requiredQualifications:QualificationCode[];requestedSlot:Slot;dueAt:Instant;offerExpiresAt:Instant;termsVersion:ID;origin:JobOrigin;visitSlot:Slot;partnerSlotProposal:PartnerSlotProposal|null};
export type JobDetail = MaintenanceJob & {projection:'detail';assignment:Assignment|null;offer:Offer|null;eventCursor:number};
export type ReportHistorySummary = {hasReport:false;acceptance:'not_accepted'}|{hasReport:true;acceptance:'accepted'|'not_accepted'};
export type JobHistorySnapshot = {projection:'history';asOf:Instant;severity:null;dueAt:null;jobId:ID;type:MaintenanceJob['type'];status:JobStatus;contractorOrgId:ID|null;completedAt:Instant|null;ownDecisionEvents:JobEvent[];redactedReportSummary:ReportHistorySummary};
export type ComponentKey = 'filter'|'evaporator_coil'|'blower_motor'|'blower_fan'|'drain_pipe'|'drain_pan'|'outlet'|'louver'|'condenser_coil'|'compressor'|'fan'|'blade'|'refrigerant_pipe'|'thermostat'|'sensor'|'capacitor'|'contactor'|'wiring';
export type InspectionItem = {id:ID;componentGroup:'indoor'|'outdoor'|'electrical';componentKey:ComponentKey;result:'normal'|'attention'|'not_inspected'|'not_applicable'|null;reason:string|null;evidenceIds:ID[];authorId:ID;observedAt:Instant};
export type Part = {name:string;quantity:number;catalogCode:string|null;source:'van_stock'|'hq_warehouse'|'bought_locally';lotSerial:string|null;replacesComponentKey:ComponentKey|null;oldPartDisposal:'disposed_on_site'|'returned'|null;receiptAttachmentId:ID|null};
export type RefrigerantRecord = {refrigerant:'R32'|'R410A';cylinderId:string;recoveredKg:number;chargedKg:number;leakCheck:'pass'|'fail'|'not_done';leakCheckMethod:string|null};
export type SignOff = {signerName:string;signedAt:Instant;signatureAttachmentId:ID|null;absentReason:string|null;sitePhotoAttachmentId:ID|null;reportVersion:number};
export type NextAction = {kind:'none'}|{kind:'follow_up';date:Instant;note:string};
/** Internal repository provenance; never returned in public WorkReport DTOs. */
export type ReportRevisionProvenance = {reportId:ID;reportVersion:number;contributorUserIds:ID[]};
export type ReviewAvailability = {allowed:true;reason:null}|{allowed:false;reason:'permission_denied'|'self_authored'|'not_current'|'not_submitted'};
export type WorkReport = Entity & {reviewAvailability:ReviewAvailability;jobId:ID;authorId:ID;items:InspectionItem[];measurements:Measurement[];parts:Part[];refrigerant:RefrigerantRecord[];signOff:SignOff|null;workText:string;nextAction:NextAction|null;attachmentRefs:Attachment[];submittedAt:Instant|null;acceptedAt:Instant|null;reviewHistory:Review[]};
export type Review = {reviewerUserId:ID;reportVersion:number;decision:'accept'|'return';reason:string|null;occurredAt:Instant};
export type WorkReportDraft = {jobId:ID;reportId?:ID;items:InspectionItemInput[];measurements:InspectionMeasurementInput[];parts:Part[];refrigerant:RefrigerantRecord[];workText:string;nextAction:NextAction|null;attachmentIds:ID[]};
export type Attachment = Entity & {jobId:ID;reportId:ID;blobId:ID;name:string;mime:'image/jpeg'|'image/png';size:number;status:'processing'|'ready'|'failed'};
export type JobNote = Entity & {jobId:ID;authorId:ID;visibility:'internal'|'customer';message:string};
export type JobEvent = Entity & {jobId:ID;actorUserId:ID;action:string;occurredAt:Instant;note:JobNote|null;reportRef:ReportRef|null};
export type MaintenancePlan = Entity & {unitId:ID;recurrence:{kind:'monthly';intervalMonths:number};timezone:'UTC';anchorDay:number;nextDueAt:Instant;generatedOccurrences:{occurrenceAt:Instant;jobId:ID}[]};
export type Contract = Entity & {activeRestrictionIds:ID[];hasUnresolvedRecovery:boolean;customerId:ID;customerOrgId:ID;unitIds:ID[];planType:'rto'|'general'|'energy'|'environment';startAt:Instant;endAt:Instant;priceMinor:number;currency:Currency;restrictionEligible:boolean;rulesVersion:ID|null};
export type Invoice = Entity & Money & {number:string;contractId:ID;contractVersion:number;period:Range;dueAt:Instant;status:'unpaid'|'processing'|'paid';paymentMethod:PaymentMethod|null;paymentStatus:Payment['status']|null;paidAt:Instant|null};
export type PaymentMethod = 'demo_credit_card'|'demo_debit_card';
export type Payment = Entity & Money & {invoiceId:ID;method:PaymentMethod|null;status:'initiated'|'processing'|'confirmed'|'failed';paymentReference:string|null;confirmedAt:Instant|null;confirmationReason:string|null;eventIds:ID[]};
export type InvoiceDetail = Invoice & {paymentRefs:Payment[];restrictionIds:ID[]};
export type RestrictionUnit = {unitId:ID;applyState:'not_sent'|'sent_unknown'|'applied'|'not_applied';releaseState:'none'|'waiting_reconcile'|'requested'|'released'|'not_required'|'failed';applyCommandIds:ID[];releaseCommandIds:ID[];observedRestriction:ObservedRestriction;observedAt:Instant|null;evidenceId:ID|null;pendingReason:string|null};
export type Restriction = Entity & {recoveryCases:RestrictionRecoveryCase[];noticeNotificationIds:ID[];contractId:ID;contractVersion:number;causeInvoiceIds:ID[];unitIds:ID[];rulesVersion:ID;noticeAt:Instant;executeAfter:Instant;reason:string;policy:RestrictionPolicy;state:'scheduled'|'requested'|'applied'|'release_requested'|'released'|'cancelled';exception:{until:Instant;reason:string|null}|null;graceUntil:Instant|null;perUnit:RestrictionUnit[];events:AuditView[];releaseIntent:ReleaseIntent|null};
/** IR96: origin of the release request; client projections mask actorMembershipId. */
export type ReleaseIntent = {source:'payment'|'exception'|'override'|'manual'|'cancel';at:Instant;actorMembershipId:ID};
export type RestrictionDetail = Restriction;
export type RestrictionReleaseView = Pick<Restriction,'id'|'version'|'createdAt'|'updatedAt'|'unitIds'|'rulesVersion'|'policy'|'state'|'perUnit'|'recoveryCases'|'noticeAt'|'executeAfter'> & {projection:'release';releaseIntent:Pick<ReleaseIntent,'source'|'at'>|null};
export type RestrictionRead = RestrictionDetail|RestrictionReleaseView;
export type Inquiry = Entity & {customerId:ID;invoiceId:ID|null;restrictionId:ID|null;subjectType:'payment'|'restriction';message:string;state:'received'|'answered';reply:string|null};
export type Device = Entity & {bindingId:ID|null;unitId:ID|null;targetUnitId:ID;createdByMembershipId:ID;serial:string;connection:Connection;lastSeenAt:Instant|null;firmwareVersion:string;powerSignal:'unknown'|'on'|'off';tamper:'clear'|'detected';sensors:Sensor[]};
export type DeviceOperation = Entity & DeviceHistoryScope & {deviceId:ID;kind:'check'|'calibrate'|'firmware';status:'queued'|'running'|'succeeded'|'failed';targetVersion:string|null;failureCode:ErrorCode|null;startedAt:Instant|null;finishedAt:Instant|null;expiresAt:Instant};
export type DeviceDetail = Device & {calibrationRefs:ID[];activeOperation:DeviceOperation|null};
export type DeviceEvent = Entity & DeviceHistoryScope & {alertIds:ID[];deviceId:ID;eventType:'communication_lost'|'power_lost'|'tamper'|'restored'|'operation_failed';recovery:DeviceRecovery|null;evidenceSource:'heartbeat'|'power_signal'|'tamper_signal';sequence:number;occurredAt:Instant;restoredAt:Instant|null;responseNotes:{actorId:ID;message:string;at:Instant}[]};
export type CalibrationRecord = Entity & DeviceHistoryScope & {deviceId:ID;sensorId:ID;metric:Metric;unit:UnitSymbol;referenceValue:number;measuredValue:number;calibratedAt:Instant;actorId:ID;isDemo:true};
export type Condition = {type:'occupancy';occupied:boolean}|{type:'location';event:'arrival'|'departure'}|{type:'pattern';localTime:string}|{type:'weather';metric:'temperature';operator:Compare;value:number}|{type:'tariff';operator:Compare;value:number;unit:'MYR_per_kWh'}|{type:'peak';active:boolean}|{type:'solar'|'battery';operator:Compare;value:number;unit:'kW'};
export type Compare = 'gt'|'gte'|'lt'|'lte';
export type RuleBase = Entity & {name:string;unitIds:ID[];ownerMembershipId:ID;createdByUserId:ID;timezone:string;enabled:boolean;priority:number;disabledReason:'capability_changed'|'unit_archived'|'consent_revoked'|null};
/** IR215: “Only if …” conditions — every one must hold when the rule runs (missing data never matches). */
export type ExtraCondition = {type:'weekday';weekdays:number[]}|{type:'occupancy';occupied:boolean}|{type:'weather';metric:'temperature';operator:Compare;value:number};
/** IR215: the latest run-log outcome of a rule — a Command, or a skip with its reason. */
export type AutomationRun = {at:Instant;outcome:'command_created'|'skipped';reason:DecisionReason|null;commandId:ID|null};
export type Automation = RuleBase & {onlyIf:ExtraCondition[];lastRun:AutomationRun|null} & ({kind:'schedule';weekdays:number[];startLocal:string;endLocal:string;endsNextDay:boolean;startAction:UnitAction;endAction:UnitAction}|{kind:'event';condition:Condition;action:UnitAction});
/** IR108: alert policies belong to one customer; units carry them (ACUnit.alertPolicyIds) and alert Policy.unitIds is the derived attachment list. Air-quality limits are alert policies (FR-A12 merged into FR-A05). */
export type ActiveWindow = {weekdays:number[];startLocal:string;endLocal:string};
export type AlertCondition = {metric:Metric;operator:Compare;threshold:number;recoveryThreshold:number;durationSeconds:number;activeWindow:ActiveWindow|null;severity:Severity};
export type DefaultAlertRule = AlertCondition & {ruleKey:ID;name:string;category:'air_quality'|'fault'|'maintenance'|'connection'};
export type DefaultRuleSetting = Entity & {policyId:ID;ruleKey:ID;customerId:ID;enabled:boolean;changedByMembershipId:ID;reason:string|null};
export type Policy = RuleBase & ({kind:'automation';condition:Condition;action:UnitAction}|({kind:'alert';customerId:ID;recipientMembershipIds:ID[];channels:Channel[];escalateAfterMinutes:number;cooldownMinutes:number} & AlertCondition)|{kind:'default_alert';customerId:null;rules:DefaultAlertRule[];ruleSettings:DefaultRuleSetting[]});
export type Consent = Entity & {membershipId:ID;purpose:'location_automation';granted:boolean;grantedAt:Instant|null;revokedAt:Instant|null};
export type Fact = {unitId:ID;metric:Metric|'weather_temperature'|'tariff'|'solar'|'battery'|'occupied'|'location'|'peak';value:number|boolean|'arrival'|'departure'|null;unit:string;observedAt:Instant;quality:Quality};
export type EvaluationInput = {eventId:ID;occurredAt:Instant;unitIds:ID[];facts:Fact[];phase:'schedule_start'|'schedule_end'|'condition'};
export type DecisionReason = 'missing_data'|'stale'|'no_match'|'consent_revoked'|'owner_forbidden'|'restricted'|'disabled'|'busy'|'offline'|'invalid_capability'|'no_control_action'|'reconciliation_required';
export type Decision = {unitId:ID;decision:'selected'|'suppressed';ruleId:ID|null;reason:DecisionReason|null};
export type SimulationResult = {eventId:ID;results:Decision[];notifications:NotificationDecision[]};
export type FireResult = {eventId:ID;results:(Omit<Decision,'decision'> & {decision:'requested'|'suppressed'|'failed';commandId:ID|null})[];notifications:NotificationOutcome[]};
export type Channel = 'inApp'|'email'|'whatsapp';
export type Target = {kind:'unit'|'job'|'invoice'|'restriction'|'device'|'inquiry'|'client_user';id:ID};
export type Notification = Entity & {sourceAlertId:ID|null;type:NotificationType;recipientMembershipId:ID;scopeVersionAtCreation:number;target:Target;templateKey:'alert'|'quality'|'schedule_change'|'report_return'|'completion'|'payment'|'payment_reminder'|'restriction'|'inquiry'|'job_update'|'device_operation'|'invite';params:{targetName:string;at:Instant;status:string;reason:string|null;amountMinor:number|null;currency:Currency|null;method:PaymentMethod|null;message:string|null};channel:Channel;deliveryState:'preview'|'simulated'|'failed';severity:Severity;occurredAt:Instant;readAt:Instant|null};
export type NotificationPreview = Notification;
export type AuditView = Entity & {actorId:ID;actorRoleAtTime:Role|'system';action:string;targetRef:{kind:string;id:ID};previousVersion:number|null;nextVersion:number|null;occurredAt:Instant;correlationId:ID;result:'success'|'denied'|'failed'|'pending';maskedBefore:Record<string,string|null>;maskedAfter:Record<string,string|null>;reason:string|null};
export type EnergyBaseline = Entity & {unitIds:ID[];period:Range;method:'demo_fixed'|'demo_period_comparison';baselineKWh:number|null;quality:BaselineQuality;boundaryId:EnergyBoundaryId;boundary:string;assumptions:string;source:string};
export type EmissionFactor = Entity & {region:string;year:number;kgCO2ePerKWh:number;source:string;isDemo:true};
export type EnergySummary = {period:Range;unitIds:ID[];totals:{kWh:number|null;amountMinor:number|null;savedKWh:number|null;deltaKWh:number|null;savingPercentage:number|null;savedAmountMinor:number|null;emissionsKg:number|null;savedEmissionsKg:number|null};currency:Currency;baselineRef:{id:ID;version:number}|null;factorRef:{id:ID;version:number}|null;baselineSnapshot:EnergyBaseline|null;factorSnapshot:EmissionFactor|null;tariffVersion:ID;boundaryId:EnergyBoundaryId;boundary:string;coverage:number|null;qualityWarnings:string[]};
export type MRVConditions = Range & {unitIds:ID[];baselineId:ID;baselineVersion:number;factorId:ID;factorVersion:number;boundaryId:EnergyBoundaryId;boundary:string;organizationId:ID};
export type MRVPreview = {conditions:MRVConditions;summary:EnergySummary;incomplete:boolean;scope:'scope_2';isDemo:true};
export type MRVReport = Entity & MRVPreview & {status:'draft'|'demo_reviewed';evidenceIds:ID[];reviewHistory:{userId:ID;reportVersion:number;comment:string;at:Instant}[]};
export type OffsetQuote = Entity & {customerId:ID;purpose:string;amountKg:number;period:Range;unitIds:ID[];estimatedAmountMinor:number|null;currency:Currency|null;expiresAt:Instant;provider:'unselected';scheme:'demo';isDemo:true;marketConcept:{stage:'future_concept';providerLabel:'unselected';verificationStatus:'unverified';ledgerStatus:'not_connected'}};
export type OffsetAttempt = {id:ID;stage:'purchase'|'retirement';status:'pending'|'succeeded'|'failed';startedAt:Instant;completedAt:Instant|null};
export type OffsetRecord = Entity & {quoteId:ID;customerId:ID;amountKg:number;attempts:OffsetAttempt[];currentAttemptId:ID|null;state:'demo_requested'|'demo_purchased'|'demo_retired'|'failed';previousState:OffsetRecord['state']|null;purchaseRef:ID|null;retirementRef:ID|null;demoCertificateRef:ID|null;eventHistory:AuditView[];isDemo:true};
export type TelemetrySummary = {measurements:Measurement[];asOf:Instant;energy:EnergySummary|null};
export type AdminSummary = {customerCount:number;total:number;online:number;offline:number;unknown:number;powerOn:number;powerOff:number;powerUnknown:number;operatingRate:number|null;alertCount:number;jobCounts:Record<JobStatus,number>;overdueInvoiceCount:number|null;amountsByCurrency:Money[]|null;billingVisibility:'allowed'|'forbidden';energySummary:EnergySummary|null;energyForecast:EnergyForecast;asOf:Instant};
/** IR78: prorated modeled-baseline forecast for the admin dashboard only; comparisons stay in energy.summary. */
export type EnergyForecast = {period:Range;unitIds:ID[];basis:'prorated_modeled_baseline';baselineRef:{id:ID;version:number}|null;baselineSnapshot:EnergyBaseline|null;expectedUnitMinutes:number;validUnitMinutes:number;actualKWhOnValidSlots:number|null;predictedBaselineKWh:number|null;predictedActualKWh:number|null;forecastSavedKWh:number|null;forecastSavingPercentage:number|null;qualityWarnings:('actual_unavailable'|'baseline_unavailable'|'modeled_baseline'|'no_units'|'partial_coverage'|'prorated_forecast')[]};
export type Summary = {kind:'customer'|'partner'|'technician';counts:{total:number;online:number;offline:number;unknown:number;powerOn:number;powerOff:number;powerUnknown:number;alertCount:number;offerCount:number;activeCount:number;reviewCount:number;scheduledCount:number;inProgressCount:number;overdueCount:number;assignedCount:number};asOf:Instant};
export type Capacity = {membershipId:ID;date:string;availableSlots:Slot[];assignedSlots:Slot[];availableMinutes:number|null;assignedMinutes:number;utilization:number|null;unavailability:Unavailability['type']|null};
export type ResolvedIntent = {kind:'unsupported'}|{kind:'help';messageKey:'voice.help'}|{kind:'candidates';candidates:{unitId:ID;pathLabel:string}[]}|{kind:'temperature';unitId:ID;measurement:Measurement|null}|{kind:'change';unitId:ID;celsius:number;before:ObservedState;expectedVersion:number};
export type ResetPreview = {messageKey:'auth.reset_generic';deliveryState:'preview'};
export type ArchivedResource = {id:ID;version:number;archived:true};
export type DemoGeneration = {generation:number};
export type DemoEvent = {eventId:ID;generation:number;occurredAt:Instant;type:string};
export type Query = {cursor?:string;limit?:number;sort?:{field:'id'|'version'|'name'|'status'|'createdAt'|'updatedAt'|'severity'|'dueAt'|'observedAt'|'occurredAt'|'periodFrom'|'startAt'|'validFrom'|'priority'|'email'|'invitedAt'|'year'|'region'|'executeAfter'|'noticeAt'|'effectiveFrom'|'expiresAt'|'period';direction:'asc'|'desc'};filters?:{search?:string;period?:string;origin?:JobOrigin;proposalPending?:boolean;contractorOrgId?:ID;statementId?:ID;campaignId?:ID;modelId?:ID;expiringWithinDays?:number;coverage?:UnitCoverage['status'];customerId?:ID;propertyId?:ID;spaceId?:ID;unitId?:ID;unitIds?:ID[];jobId?:ID;contractId?:ID;invoiceId?:ID;restrictionId?:ID;organizationId?:ID;membershipId?:ID;kind?:string;status?:string;statuses?:string[];overdueOnly?:boolean;includeDescendants?:boolean;connections?:Connection[];powerState?:'on'|'off'|'unknown';unassignedOnly?:boolean;severity?:Severity;enabled?:boolean;unreadOnly?:boolean;from?:Instant;to?:Instant;date?:string;qualification?:QualificationCode;activeOnly?:boolean;actorId?:ID;targetKind?:Target['kind'];targetId?:ID;action?:string;correlationId?:ID;result?:AuditView['result'];method?:'demo_fixed'|'demo_period_comparison';boundaryId?:string;region?:string;year?:number;subjectType?:Inquiry['subjectType'];role?:Role;type?:NotificationType;clientRole?:ClientRole;code?:QualificationCode|'other'}};
export type Save<T> = Omit<T,keyof Entity|'ownerMembershipId'|'createdByUserId'> & {id?:ID};
export type BlobInput = {name:string;mime:'image/jpeg'|'image/png';size:number;bytes:Uint8Array};
export type DocumentInput = {name:string;mime:'application/pdf'|'image/jpeg'|'image/png';size:number;bytes:Uint8Array};


export type RuleInput = {id?:ID;name:string;unitIds:ID[];timezone:string;enabled:boolean;priority:number};
export type AlertPolicyInput = Omit<RuleInput,'unitIds'> & Omit<Extract<Policy,{kind:'alert'}>,keyof RuleBase>;
/** IR120: HQ edits the six default-rule limits; ruleKeys, order, names and categories are fixed. */
export type DefaultPolicyInput = {id:ID;kind:'default_alert';rules:DefaultAlertRule[]};
export type PolicyInput = (RuleInput & Omit<Extract<Policy,{kind:'automation'}>,keyof RuleBase>)|AlertPolicyInput|DefaultPolicyInput;
/** IR214: automationId is null for a draft preview. */
export type ScheduledOccurrence = {automationId:ID|null;phase:'schedule_start'|'schedule_end';at:Instant;action:UnitAction};
/** IR214: the unsaved schedule of the C04 editor, validated like automations.save. */
export type ScheduleDraft = {timezone:string;weekdays:number[];startLocal:string;endLocal:string;endsNextDay:boolean;startAction:UnitAction;endAction:UnitAction};
export type DeletedResource = {id:ID;deleted:true};
export type WriteResult = {state:'not_received'|'pending'}|{state:'succeeded';operation:string;resourceIds:ID[];result:WriteResultData}|{state:'failed';error:DomainError};
export type WriteResultData = { [K in keyof OperationContracts]: OperationContracts[K]['mode'] extends 'write' ? OperationContracts[K]['result'] : never }[keyof OperationContracts];
export type DemoTrigger = {scenarioId:string;eventId:ID;occurredAt:Instant} & ({eventType:'command_sent'|'command_ack'|'command_fail';commandId:ID;sequence:number}|{eventType:'telemetry';measurement:RawMeasurement}|({eventType:'device';deviceId:ID;bindingId:ID|null;sequence:number} & ({kind:'communication_lost'|'power_lost'|'tamper'}|{kind:'restored';recovery:DeviceRecovery}))|{eventType:'qualification_revoked';membershipId:ID;qualification:QualificationCode}|{eventType:'operation';operationId:ID;result:'succeeded'|'failed'}|{eventType:'automation';event:EvaluationInput}|{eventType:'network';connected:boolean}|{eventType:'simulator';enabled:boolean}|{eventType:'allergen';observation:{unitId:ID} & AllergenObservation}|{eventType:'load_alert';unitId:ID;causeCode:Alert['causeCode'];evidenceKind:Alert['evidenceKind'];evidenceText:string;severity:Severity}|{eventType:'session_expired'|'microphone_denied'}|{eventType:'restriction_observation';restrictionId:ID;unitId:ID;observed:ObservedRestriction;sequence:number}|{eventType:'transport';operation:OperationName;outcome:'UNAVAILABLE'|'TIMEOUT'|'RATE_LIMITED'|'DELAY';retryAfterSeconds:number|null;delayMs:number|null;remainingCalls:number});

export type ScopeRef = {kind:'tenant'|'organization'|'property'|'unit';id:ID};
export type QualificationCode = 'demo_indoor'|'demo_outdoor'|'demo_electrical';
export type QualificationGrant = {code:QualificationCode;validFrom:Instant;validUntil:Instant;revokedAt:Instant|null};
export type EffectivePowerState = 'on'|'off'|'unknown';
export type ControlAvailability = {state:'available'}|{state:'blocked';reasonKey:'control.reconciliation_required'};
export type DeviceHistoryScope = {bindingId:ID|null;unitIdAtOccurrence:ID;customerOrgIdAtOccurrence:ID};
export type DeviceBinding = Entity & {deviceId:ID;unitId:ID;customerOrgId:ID;boundAt:Instant;unboundAt:Instant|null};
export type RestrictionRecoveryCase = {id:ID;unitId:ID;observedRestrictionId:ID;observedRulesVersion:ID;successorRestrictionId:ID|null;state:'pending'|'removing'|'resolved';observationEventId:ID;commandIds:ID[];createdAt:Instant;resolvedAt:Instant|null};
export type BaselineQuality = {kind:'modeled';coverage:null;expectedSlots:null;validSlots:null;sourceSnapshot:null}|{kind:'measured';coverage:number;expectedSlots:number;validSlots:number;sourceSnapshot:{generation:number;eventCursor:number;snapshotAt:Instant}};
export type BaselineInput = {id?:ID;unitIds:ID[];period:Range;boundaryId:EnergyBoundaryId;boundary:string;assumptions:string;source:string} & ({method:'demo_fixed';baselineKWh:number}|{method:'demo_period_comparison'});
export type EffectiveControlPolicy = {state:'unrestricted'}|{state:'restricted';phase:'requested'|'applied'|'release_requested';policy:RestrictionPolicy;reasonKey:'control.restriction_active'};
export type InspectionItemInput = {componentGroup:InspectionItem['componentGroup'];componentKey:ComponentKey;result:InspectionItem['result'];reason:string|null;evidenceIds:ID[]};
export type InspectionMeasurementInput = {id?:ID;componentKey:ComponentKey;metric:Metric;value:number|null;unit:UnitSymbol;observedAt:Instant};
export type DeliveryFailure = {id:ID;policyId:ID|null;eventId:ID;occurredAt:Instant;reason:'no_recipient';deliveryState:'failed'};
export type DeviceRecovery = {axis:'connection';sourceEventId:ID;value:'online'}|{axis:'power';sourceEventId:ID;value:'on'}|{axis:'tamper';sourceEventId:ID;value:'clear'};
export type NotificationDecision = {unitId:ID;policyId:ID;decision:'selected'|'suppressed'|'failed';reason:'not_due'|'quality'|'disabled'|'owner_forbidden'|'cooldown'|'no_recipient'|null};
export type NotificationOutcome = {unitId:ID;policyId:ID;decision:'created'|'suppressed'|'failed';reason:'not_due'|'quality'|'disabled'|'owner_forbidden'|'cooldown'|'no_recipient'|null;notificationIds:ID[];failureIds:ID[]};

export type EnergyBoundaryId = 'ac_input_electricity'|'whole_building_electricity';
export type MeasurementIssue = 'unit_mismatch'|'non_finite'|'out_of_range'|'invalid_time';
export type RawMeasurement = {unitId:ID;sensorId:ID;metric:Metric;value:number|null;unit:string;observedAt:Instant;receivedAt:Instant;origin:Measurement['origin'];quality:Quality;sequence?:number;eventId:ID}; // IR77: omitted sequence = latest+1
export type JobDecisionReceipt = {jobId:ID;jobVersion:number;offerId:ID;decision:'accept'|'decline'};
export type NotificationType = 'cleaning_due'|'fault'|'quality'|'schedule_change'|'report_return'|'completion'|'payment'|'payment_reminder'|'restriction'|'inquiry'|'job_update'|'device_operation';
export type InvoiceReminderReceipt = {invoiceId:ID;invoiceVersion:number;notificationId:ID};

/** IR107–IR112: Figma-confirmed screens (2026-10-01). */
export type ClientRole = 'owner'|'member';
export type ClientUser = Entity & {customerId:ID;membershipId:ID|null;email:string;displayName:string|null;clientRole:ClientRole;status:'invited'|'active'|'disabled';lastSignInAt:Instant|null;allowedChannels:Channel[];invitedAt:Instant;invitedByMembershipId:ID};
export type LocationTarget = {kind:'property'|'space'|'unit';id:ID};
export type VentilationLog = Entity & {spaceId:ID;unitId:ID|null;method:'window_opened'|'door_opened'|'ventilation_fan'|'other';durationMinutes:number;co2AtLog:{value:number;unit:'ppm';observedAt:Instant}|null;loggedByMembershipId:ID;loggedAt:Instant};
export type ImportRow = {rowNumber:number;propertyName:string;floorName:string|null;roomName:string|null;unitName:string;modelCode:string;serial:string|null;installedOn:string|null;warrantyEnd:string|null;result:'ready'|'warning'|'error';messageKey:string|null};
export type ImportPreview = {previewId:ID;customerId:ID;fileName:string;rows:ImportRow[];readyCount:number;warningCount:number;errorCount:number;expiresAt:Instant};
export type UnitImport = Entity & {customerId:ID;previewId:ID;createdPropertyIds:ID[];createdSpaceIds:ID[];createdUnitIds:ID[];skippedRowNumbers:number[];undoUntil:Instant;state:'imported'|'undone'};
export type WarrantyClaim = {id:ID;partLabel:string;amountMinor:number;currency:Currency;state:'claimable'|'filed';filedAt:Instant|null;reason:string|null};
export type UnitCoverage = {unitId:ID;customerId:ID;modelId:ID;warrantyEndsAt:Instant|null;contractIds:ID[];status:'under_warranty'|'contract'|'expiring'|'no_coverage';claimableJobIds:ID[]};
export type FirmwareCampaignResult = {deviceId:ID;waveIndex:number;status:'pending'|'installing'|'succeeded'|'failed'|'skipped';reasonKey:string|null;operationId:ID|null;at:Instant|null};
export type FirmwareCampaign = Entity & {modelId:ID;fromVersions:string[];targetVersion:string;checksum:string;deviceIds:ID[];waves:{label:string;percent:number}[];window:{startLocal:string;endLocal:string};autoPauseFailurePercent:number;startAt:Instant;state:'scheduled'|'running'|'paused'|'aborted'|'completed';progress:{succeeded:number;installing:number;pending:number;failed:number;skipped:number};results:FirmwareCampaignResult[];reason:string|null};
export type ContractorKpis = {period:Range;offerAcceptance:number|null;arrivalInWindow:number|null;firstTimeAccepted:number|null;averageRating:number|null;ratingCount:number;reworkRate:number|null};
export type ContractorProfile = Entity & {organizationId:ID;name:string;status:'active'|'suspended';registrationNo:string;serviceAreas:string[];contactEmail:string;insuranceValidUntil:Instant|null;delegation:Range;rateCardId:ID|null;suspendedReason:string|null;kpis:ContractorKpis};
export type RateCard = Entity & {contractorOrgId:ID;effectiveFrom:Instant;currency:Currency;lines:{workType:'periodic_inspection'|'repair_base'|'emergency'|'rework_deduction';amountMinor:number;note:string|null}[]};
export type Certificate = Entity & {membershipId:ID;organizationId:ID;code:QualificationCode|'other';name:string;number:string;issuedAt:Instant;expiresAt:Instant;fileName:string|null;status:'valid'|'expiring'|'expired'|'pending_verification'|'rejected';renewalOf:ID|null;verifiedByMembershipId:ID|null;verifiedAt:Instant|null;trainingRequestedAt:Instant|null};
export type Unavailability = Entity & {organizationId:ID;membershipId:ID|null;from:string;to:string;type:'annual_leave'|'training'|'public_holiday'|'sick'|'other';note:string|null;conflictingAssignmentIds:ID[]};
export type SlaMetrics = {responseWithinTarget:number|null;arrivalInWindow:number|null;firstTimeFix:number|null;averageRating:number|null;ratingCount:number;openOverdue:number};
export type SlaTargets = Entity & {planType:Contract['planType'];responseHours:number;arrivalInWindowPercent:number;firstTimeFixPercent:number;effectiveFrom:Instant};
export type SlaScorecard = {period:Range;contractorOrgId:ID|null;totals:SlaMetrics;customers:(SlaMetrics & {customerId:ID;jobCount:number;status:'on_track'|'at_risk'|'breached'})[];breaches:{jobId:ID;customerId:ID;kind:'response'|'arrival'|'first_time_fix'|'overdue';detail:string}[]};
export type PayoutLine = {id:ID;jobId:ID;workType:RateCard['lines'][number]['workType'];acceptedAt:Instant|null;amountMinor:number;kind:'charge'|'deduction'|'adjustment';note:string|null};
export type PayoutQuestion = {id:ID;lineId:ID;topic:'amount'|'deduction'|'missing_job'|'other';message:string;state:'open'|'answered'|'adjusted';reply:string|null;adjustmentMinor:number|null};
export type PayoutStatement = Entity & {contractorOrgId:ID;period:string;status:'draft'|'approved'|'paid';currency:Currency;grossMinor:number;deductionsMinor:number;netMinor:number;payDate:Instant;lines:PayoutLine[];queries:PayoutQuestion[];approvedByMembershipId:ID|null;paidAt:Instant|null};
export type TwoFactorStatus = {enabled:boolean;enabledAt:Instant|null;recoveryCodesLeft:number|null;setupKey:string|null};
export type JobRating = {stars:1|2|3|4|5;tags:string[];comment:string|null;ratedAt:Instant;editableUntil:Instant};
export type TimeOnSite = {arrivedAt:Instant|null;checkInMethod:'location_qr'|'manual'|null;checkInReason:string|null;distanceMeters:number|null;startedAt:Instant|null;pauses:{from:Instant;to:Instant|null}[];finishedAt:Instant|null;onSiteMinutes:number|null};
export type FilterCareStatus = {unitId:ID;runHoursSinceCleaning:number|null;thresholdHours:number;fallbackDays:number;lastCleanedAt:Instant|null;lastCleanedBy:'customer'|'technician'|null;lastCleaningJobId:ID|null;status:'ok'|'due_soon'|'overdue'|'unknown'};
export type FilterCareSettings = Entity & {customerId:ID;thresholdHours:number|null;fallbackDays:number;recipients:'owners'|'all_users';channels:Channel[]};
export type ReportFile = {fileName:string;mime:'application/pdf'|'text/csv';size:number;generatedAt:Instant;isDemo:true};
export type QrResolution = {unitId:ID;jobId:ID|null};
export type PartCatalogItem = {code:string;name:string;vanStockQuantity:number|null};

export type OperationContracts = {
  'invoices.remind': {input:{invoiceId:ID;recipientMembershipId:ID;channel:Channel;reason:string};result:InvoiceReminderReceipt;mode:'write'};
  'mrv.versions': {input:{id:ID;query:Query};result:Page<MRVReport>;mode:'read'};
  'diagnosticRuns.list': {input:{unitId:ID;jobId?:ID;query:Query};result:Page<DiagnosticRun>;mode:'read'};
  'devices.operations': {input:{deviceId:ID;query:Query};result:Page<DeviceOperation>;mode:'read'};
  'devices.calibrations': {input:{deviceId:ID;query:Query};result:Page<CalibrationRecord>;mode:'read'};
  'admin.summary': {input:Range & {customerId?:ID;propertyId?:ID};result:AdminSummary;mode:'read'};
  'alerts.acknowledge': {input:{alertId:ID};result:Alert;mode:'write'};
  'alerts.get': {input:{id:ID};result:Alert;mode:'read'};
  'alerts.list': {input:Query;result:Page<Alert>;mode:'read'};
  'alerts.resolve': {input:{alertId:ID;resolutionReason:string;resolutionEvidenceIds:ID[]};result:Alert;mode:'write'};
  'attachments.add': {input:{jobId:ID;reportId:ID;file:BlobInput};result:Attachment;mode:'write'};
  'attachments.getContent': {input:{jobId:ID;reportId:ID;reportVersion:number;attachmentId:ID};result:Blob;mode:'read'};
  'audit.list': {input:Query;result:Page<AuditView>;mode:'read'};
  'auth.previewPasswordReset': {input:{demoEmail:string};result:ResetPreview;mode:'read'};
  'automations.delete': {input:{id:ID};result:DeletedResource;mode:'write'};
  'automations.fire': {input:EvaluationInput;result:FireResult;mode:'write'};
  'automations.list': {input:Query;result:Page<Automation>;mode:'read'};
  'automations.nextRuns': {input:{automationId:ID;count:8}|{draft:ScheduleDraft;count:8};result:ScheduledOccurrence[];mode:'read'};
  'automations.save': {input:RuleInput & {onlyIf?:ExtraCondition[]} & ({kind:'schedule';weekdays:number[];startLocal:string;endLocal:string;endsNextDay:boolean;startAction:UnitAction;endAction:UnitAction}|{kind:'event';condition:Condition;action:UnitAction});result:Automation;mode:'write'};
  'automations.simulate': {input:EvaluationInput;result:SimulationResult;mode:'read'};
  'baselines.list': {input:Query;result:Page<EnergyBaseline>;mode:'read'};
  'baselines.save': {input:BaselineInput;result:EnergyBaseline;mode:'write'};
  'capabilities.list': {input:Query;result:Page<Capability>;mode:'read'};
  'capabilities.save': {input:Save<Capability> & {changeReason?:string};result:Capability;mode:'write'};
  'commands.create': {input:{unitId:ID;action:UnitAction;jobId?:ID;reason?:string;expectedUnitVersion:number};result:Command;mode:'write'};
  'commands.get': {input:{id:ID};result:Command;mode:'read'};
  'commands.list': {input:{unitId:ID;jobId?:ID;query:Query};result:Page<Command>;mode:'read'};
  'consents.get': {input:{purpose:'location_automation'};result:Consent;mode:'read'};
  'consents.update': {input:{purpose:'location_automation';granted:boolean};result:Consent;mode:'write'};
  'contracts.list': {input:Query;result:Page<Contract>;mode:'read'};
  'contracts.save': {input:{id?:ID;customerId:ID;unitIds:ID[];planType:Contract['planType'];startAt:Instant;endAt:Instant;priceMinor:number;currency:Currency;restrictionEligible:boolean;rulesVersion:ID|null};result:Contract;mode:'write'};
  'customers.list': {input:Query;result:Page<Customer>;mode:'read'};
  'customers.save': {input:{id?:ID;name:string;organizationId:ID;serviceProfile:Customer['serviceProfile'];status:'active'|'inactive'};result:Customer;mode:'write'};
  'demo.advanceClock': {input:{to:Instant};result:DemoGeneration;mode:'write'};
  'demo.reset': {input:{confirmation:true};result:DemoGeneration;mode:'write'};
  'demo.trigger': {input:DemoTrigger;result:DemoEvent;mode:'write'};
  'demoSession.signIn': {input:{demoActorId:ID;returnTo?:string};result:Session;mode:'write'};
  'demoSession.signOut': {input:Record<string,never>;result:undefined;mode:'write'};
  'demoSession.switchMembership': {input:{demoMembershipId:ID};result:Session;mode:'write'};
  'demoSession.extend': {input:Record<string,never>;result:Session;mode:'write'};
  'devices.addResponseNote': {input:{deviceId:ID;eventId:ID;responseNote:string};result:DeviceEvent;mode:'write'};
  'devices.bind': {input:{deviceId:ID;unitId:ID;jobId?:ID;reason:string};result:Device;mode:'write'};
  'devices.calibrate': {input:{deviceId:ID;sensorId:ID;metric:Metric;unit:UnitSymbol;referenceValue:number;measuredValue:number;calibratedAt:Instant;jobId?:ID};result:CalibrationRecord;mode:'write'};
  'devices.check': {input:{id:ID;jobId?:ID};result:DeviceOperation;mode:'write'};
  'devices.events': {input:{id:ID;query:Query};result:Page<DeviceEvent>;mode:'read'};
  'devices.get': {input:{id:ID};result:DeviceDetail;mode:'read'};
  'devices.list': {input:Query;result:Page<Device>;mode:'read'};
  'devices.register': {input:{serial:string;sensorTypes:Metric[];unitId:ID;jobId?:ID};result:Device;mode:'write'};
  'devices.updateFirmware': {input:{deviceId:ID;firmwareVersion:string;jobId?:ID};result:DeviceOperation;mode:'write'};
  'diagnosticRuns.create': {input:{jobId:ID;unitId:ID;startAction:UnitAction;endAction:UnitAction;durationMinutes:number;reason:string;expectedUnitVersion:number;expectedJobVersion:number};result:DiagnosticRun;mode:'write'};
  'diagnosticRuns.get': {input:{diagnosticRunId:ID};result:DiagnosticRun;mode:'read'};
  'energy.summary': {input:Range & {unitIds:ID[];baselineId?:ID;tariffVersion?:ID};result:EnergySummary;mode:'read'};
  'factors.list': {input:Query;result:Page<EmissionFactor>;mode:'read'};
  'factors.save': {input:Save<EmissionFactor>;result:EmissionFactor;mode:'write'};
  'inquiries.answer': {input:{inquiryId:ID;reply:string};result:Inquiry;mode:'write'};
  'inquiries.create': {input:{subjectType:'payment'|'restriction';invoiceId?:ID;restrictionId?:ID;message:string};result:Inquiry;mode:'write'};
  'inquiries.list': {input:Query;result:Page<Inquiry>;mode:'read'};
  'invoices.create': {input:Money & {contractId:ID;contractVersion:number;period:Range;dueAt:Instant};result:Invoice;mode:'write'};
  'invoices.get': {input:{id:ID};result:InvoiceDetail;mode:'read'};
  'invoices.list': {input:Query;result:Page<Invoice>;mode:'read'};
  'jobs.accept': {input:{jobId:ID;offerId:ID;termsVersion:ID};result:JobDecisionReceipt;mode:'write'};
  'jobs.addNote': {input:{jobId:ID;message:string;visibility:'internal'|'customer'};result:JobNote;mode:'write'};
  'jobs.assign': {input:{jobId:ID;technicianMembershipId:ID;startAt:Instant;endAt:Instant;reason?:string};result:MaintenanceJob;mode:'write'};
  'jobs.cancel': {input:{jobId:ID;cancelReason:string};result:MaintenanceJob;mode:'write'};
  'jobs.create': {input:{unitId:ID;type:MaintenanceJob['type'];symptom:string;requestedStart:Instant;requestedEnd:Instant;alternativeSlots:Slot[];contactWindow?:string;dueAt?:Instant};result:MaintenanceJob;mode:'write'};
  'jobs.decline': {input:{jobId:ID;offerId:ID;reason:string};result:JobDecisionReceipt;mode:'write'};
  'jobs.events': {input:{jobId:ID;query:Query};result:Page<JobEvent>;mode:'read'};
  'jobs.extendAccess': {input:{jobId:ID;accessValidUntil:Instant;reason:string};result:MaintenanceJob;mode:'write'};
  'jobs.get': {input:{jobId:ID};result:JobDetail|JobOfferSummary|JobHistorySnapshot;mode:'read'};
  'jobs.hold': {input:{jobId:ID;reason:string};result:MaintenanceJob;mode:'write'};
  'jobs.list': {input:Query;result:Page<JobSummary|JobOfferSummary|JobHistorySnapshot>;mode:'read'};
  'jobs.offer': {input:{jobId:ID;contractorOrgId:ID;visitSlot:Slot;offerExpiresAt:Instant;accessValidFrom:Instant;accessValidUntil:Instant;termsVersion:ID};result:MaintenanceJob;mode:'write'};
  'jobs.resumeHold': {input:{jobId:ID;reason:string};result:MaintenanceJob;mode:'write'};
  'jobs.resumeRework': {input:{jobId:ID};result:MaintenanceJob;mode:'write'};
  'jobs.review': {input:{jobId:ID;reportVersion:number;decision:'accept'|'return';reason?:string;reviewMode:'normal'|'hq_escalation'};result:MaintenanceJob;mode:'write'};
  'jobs.saveCost': {input:{jobId:ID;costLines:CostLine[]};result:MaintenanceJob;mode:'write'};
  'jobs.saveDraft': {input:WorkReportDraft;result:WorkReport;mode:'write'};
  'jobs.start': {input:{jobId:ID;startConfirmed:true};result:MaintenanceJob;mode:'write'};
  'jobs.submit': {input:{jobId:ID;reportVersion:number};result:MaintenanceJob;mode:'write'};
  'jobs.proposeSlot': {input:{jobId:ID;slot:Slot;hold:SlotHold;message:string;replyBy:Instant};result:MaintenanceJob;mode:'write'};
  'jobs.withdrawProposal': {input:{jobId:ID;proposalId:ID};result:MaintenanceJob;mode:'write'};
  'jobs.respondProposal': {input:{jobId:ID;proposalId:ID;decision:'accept'|'decline';declineReason?:SlotProposal['declineReason'];comment?:string;preferredSlots?:Slot[]};result:MaintenanceJob;mode:'write'};
  'jobs.requestReschedule': {input:{jobId:ID;preferredSlots:Slot[];comment?:string};result:MaintenanceJob;mode:'write'};
  'jobs.proposePartnerSlot': {input:{jobId:ID;offerId:ID;slot:Slot;technicianMembershipId:ID;reason:string};result:MaintenanceJob;mode:'write'};
  'jobs.withdrawPartnerSlot': {input:{jobId:ID;proposalId:ID};result:MaintenanceJob;mode:'write'};
  'jobs.resolvePartnerSlot': {input:{jobId:ID;proposalId:ID;decision:'send_to_client'|'keep';replyBy?:Instant};result:MaintenanceJob;mode:'write'};
  'jobs.acknowledgeAssignment': {input:{jobId:ID;decision:'accept'|'cant_make';reason?:string;alternativeSlot?:Slot|null};result:Assignment;mode:'write'};
  'members.capacity': {input:{date:string;query:Query};result:Page<Capacity>;mode:'read'};
  'members.eligible': {input:{jobId:ID;startAt:Instant;endAt:Instant;query:Query};result:Page<Membership>;mode:'read'};
  'members.list': {input:Query;result:Page<Membership>;mode:'read'};
  'members.save': {input:{id?:ID;userId:ID;organizationId:ID;role:Role;employment:Membership["employment"];permissions:Permission[];scopes:ScopeRef[];validFrom:Instant;validUntil:Instant|null;reason:string};result:Membership;mode:'write'};
  'mrv.get': {input:{id:ID;reportVersion?:number};result:MRVReport;mode:'read'};
  'mrv.list': {input:Query;result:Page<MRVReport>;mode:'read'};
  'mrv.preview': {input:MRVConditions;result:MRVPreview;mode:'read'};
  'mrv.recordReview': {input:{reportId:ID;reportVersion:number;reviewComment:string};result:MRVReport;mode:'write'};
  'mrv.saveDraft': {input:{id?:ID;conditions:MRVConditions;evidenceIds:ID[]};result:MRVReport;mode:'write'};
  'notifications.list': {input:Query;result:Page<Notification>;mode:'read'};
  'notifications.markRead': {input:{id:ID};result:Notification;mode:'write'};
  'notifications.recipients': {input:{target:Target;templateKey:Notification['templateKey'];channel:Channel;role?:Role;query:Query};result:Page<NotificationRecipient>;mode:'read'};
  'notifications.preview': {input:{target:Target;templateKey:Notification['templateKey'];channel:Channel;recipientMembershipId:ID;sourceAlertId?:ID;message?:string;reason?:string};result:NotificationPreview;mode:'read'};
  'offsets.list': {input:Query;result:Page<OffsetRecord>;mode:'read'};
  'offsets.preview': {input:{customerId?:ID;purpose:string;amountKg:number;period:Range;unitIds:ID[]};result:OffsetQuote;mode:'write'};
  'offsets.simulate': {input:({event:'request';quoteId:ID;quoteVersion:number}|{event:'purchase_confirm'|'retire'|'fail';recordId:ID;attemptId:ID;eventId:ID}|{event:'retry';recordId:ID;attemptId:ID}) & {demoConfirmed:true};result:OffsetRecord;mode:'write'};
  'organizations.list': {input:Query;result:Page<Organization>;mode:'read'};
  'organizations.save': {input:Save<Organization>;result:Organization;mode:'write'};
  'payments.confirm': {input:{paymentId:ID;paymentReference:string;confirmedAmountMinor:number;currency:Currency;reason:string};result:Payment;mode:'write'};
  'payments.recordManual': {input:{invoiceId:ID;paymentReference:string;confirmedAmountMinor:number;currency:Currency;reason:string};result:Payment;mode:'write'};
  'payments.simulate': {input:{event:'initiate';invoiceId:ID;method:PaymentMethod;demoConfirmed:true}|{event:'instructions';invoiceId:ID;demoConfirmed:true}|{event:'processing'|'confirm'|'fail';paymentId:ID;eventId:ID;paymentReference:string};result:Payment|NotificationPreview;mode:'write'};
  'plans.get': {input:{id:ID};result:MaintenancePlan;mode:'read'};
  'plans.list': {input:Query;result:Page<MaintenancePlan>;mode:'read'};
  'plans.generateNext': {input:{id:ID;occurrenceDate:Instant};result:MaintenanceJob;mode:'write'};
  'plans.save': {input:{id?:ID;unitId:ID;recurrence:MaintenancePlan["recurrence"];nextDueAt:Instant};result:MaintenancePlan;mode:'write'};
  'policies.get': {input:{policyId:ID};result:Policy;mode:'read'};
  'policies.list': {input:Query;result:Page<Policy>;mode:'read'};
  'policies.save': {input:PolicyInput;result:Policy;mode:'write'};
  'preferences.get': {input:Record<string,never>;result:Preferences;mode:'read'};
  'preferences.update': {input:{locale:Locale;timezone:string;monthlyReportEmail?:boolean};result:Preferences;mode:'write'};
  'properties.archive': {input:{id:ID;reason:string};result:ArchivedResource;mode:'write'};
  'properties.list': {input:Query;result:Page<Property>;mode:'read'};
  'properties.save': {input:{id?:ID;customerOrgId:ID;kind:'home'|'office';name:string;address:string|null;accessInstructions:string|null};result:Property;mode:'write'};
  'reports.get': {input:{jobId:ID;reportId:ID;reportVersion:number};result:WorkReport;mode:'read'};
  'restrictions.cancel': {input:{restrictionId:ID;reason:string};result:Restriction;mode:'write'};
  'restrictions.defer': {input:{restrictionId:ID;until:Instant;reason:string};result:Restriction;mode:'write'};
  'restrictions.execute': {input:{restrictionId:ID;confirmedRulesVersion:ID};result:Restriction;mode:'write'};
  'restrictions.exempt': {input:{restrictionId:ID;until:Instant;reason:string};result:Restriction;mode:'write'};
  'restrictions.forInvoice': {input:{invoiceId:ID;query:Query};result:Page<RestrictionDetail>;mode:'read'};
  'restrictions.get': {input:{id:ID};result:RestrictionRead;mode:'read'};
  'restrictions.list': {input:Query;result:Page<RestrictionRead>;mode:'read'};
  'restrictions.override': {input:{restrictionId:ID;reason:string};result:RestrictionReleaseView;mode:'write'};
  'restrictions.reconcile': {input:{restrictionId:ID;unitIds:ID[]};result:RestrictionRead;mode:'write'};
  'restrictions.release': {input:{restrictionId:ID};result:Restriction;mode:'write'};
  'restrictions.retry': {input:{restrictionId:ID;unitIds:ID[];phase:'apply'|'release';confirmedRulesVersion:ID;reason:string};result:RestrictionRead;mode:'write'};
  'restrictions.schedule': {input:{contractId:ID;expectedContractVersion:number;causeInvoiceIds:ID[];unitIds:ID[];policy:RestrictionPolicy;executeAfter:Instant;reason:string;rulesVersion:ID};result:Restriction;mode:'write'};
  'session.get': {input:Record<string,never>;result:Session;mode:'read'};
  'spaces.archive': {input:{id:ID;reason:string};result:ArchivedResource;mode:'write'};
  'spaces.list': {input:Query;result:Page<Space>;mode:'read'};
  'spaces.save': {input:{id?:ID;propertyId:ID;parentSpaceId:ID|null;kind:Space['kind'];name:string};result:Space;mode:'write'};
  'summaries.get': {input:{kind:'customer'|'partner'|'technician';filters:Query['filters']};result:Summary;mode:'read'};
  'telemetry.series': {input:Range & {unitIds?:ID[];spaceId?:ID;metric:Metric;sensorId?:ID;query:Query};result:AirSeries;mode:'read'};
  'telemetry.summary': {input:Range & {unitIds:ID[];metric?:Metric};result:TelemetrySummary;mode:'read'};
  'units.archive': {input:{id:ID;reason:string};result:ArchivedResource;mode:'write'};
  'units.delete': {input:{id:ID;reason:string};result:DeletedResource;mode:'write'};
  'units.get': {input:{id:ID;jobId?:ID};result:UnitDetail;mode:'read'};
  'units.list': {input:Query;result:Page<UnitSummary>;mode:'read'};
  'units.save': {input:{id?:ID;customerOrgId:ID;propertyId:ID;spaceId:ID|null;displayName:string;modelId:ID;type:'split';installedAt:Instant|null;warrantyEndsAt?:Instant|null;serviceScope:ACUnit['serviceScope'];changeReason?:string};result:ACUnit;mode:'write'};
  'voice.resolveIntent': {input:{text:string;locale:Locale;selectedUnitId?:ID};result:ResolvedIntent;mode:'read'};
  'locations.rename': {input:{target:LocationTarget;name:string};result:Property|Space|ACUnit;mode:'write'};
  'units.setAlertPolicies': {input:{unitId:ID;alertPolicyIds:ID[]};result:ACUnit;mode:'write'};
  'policies.setDefaultRule': {input:{policyId:ID;ruleKey:ID;customerId:ID;enabled:boolean;reason?:string};result:DefaultRuleSetting;mode:'write'};
  'policies.delete': {input:{policyId:ID};result:DeletedResource;mode:'write'};
  'ventilation.log': {input:{spaceId:ID;unitId?:ID;method:VentilationLog['method'];durationMinutes:number};result:VentilationLog;mode:'write'};
  'ventilation.list': {input:Query;result:Page<VentilationLog>;mode:'read'};
  'clientUsers.list': {input:Query;result:Page<ClientUser>;mode:'read'};
  'clientUsers.save': {input:{id?:ID;customerId:ID;email:string;clientRole:ClientRole;status?:'active'|'disabled';reason?:string};result:ClientUser;mode:'write'};
  'clientUsers.remove': {input:{id:ID;reason:string};result:DeletedResource;mode:'write'};
  'clientUsers.resendInvite': {input:{id:ID};result:NotificationPreview;mode:'read'};
  'units.importPreview': {input:{customerId:ID;fileName:string;csvText:string;mapping:Record<string,string>};result:ImportPreview;mode:'read'};
  'units.importCommit': {input:{previewId:ID;customerId:ID};result:UnitImport;mode:'write'};
  'units.importUndo': {input:{importId:ID;reason:string};result:UnitImport;mode:'write'};
  'units.coverage': {input:Query;result:Page<UnitCoverage>;mode:'read'};
  'jobs.recordWarrantyClaim': {input:{jobId:ID;partLabel:string;amountMinor:number;currency:Currency;reason:string};result:MaintenanceJob;mode:'write'};
  'firmwareCampaigns.list': {input:Query;result:Page<FirmwareCampaign>;mode:'read'};
  'firmwareCampaigns.get': {input:{id:ID};result:FirmwareCampaign;mode:'read'};
  'firmwareCampaigns.schedule': {input:{modelId:ID;targetVersion:string;deviceIds:ID[];waves:FirmwareCampaign['waves'];window:FirmwareCampaign['window'];autoPauseFailurePercent:number;startAt:Instant};result:FirmwareCampaign;mode:'write'};
  'firmwareCampaigns.control': {input:{campaignId:ID;action:'pause'|'resume'|'abort'|'retry_device';deviceId?:ID;reason?:string};result:FirmwareCampaign;mode:'write'};
  'contractors.list': {input:Query;result:Page<ContractorProfile>;mode:'read'};
  'contractors.save': {input:{id?:ID;organizationId:ID;registrationNo:string;serviceAreas:string[];contactEmail:string;insuranceValidUntil:Instant|null};result:ContractorProfile;mode:'write'};
  'contractors.setOfferStatus': {input:{contractorOrgId:ID;status:'active'|'suspended';reason:string};result:ContractorProfile;mode:'write'};
  'rateCards.list': {input:Query;result:Page<RateCard>;mode:'read'};
  'rateCards.save': {input:{contractorOrgId:ID;effectiveFrom:Instant;currency:Currency;lines:RateCard['lines']};result:RateCard;mode:'write'};
  'certificates.list': {input:Query;result:Page<Certificate>;mode:'read'};
  'certificates.submit': {input:{membershipId:ID;code:Certificate['code'];name:string;number:string;issuedAt:Instant;expiresAt:Instant;file:DocumentInput;renewalOf?:ID};result:Certificate;mode:'write'};
  'certificates.verify': {input:{certificateId:ID;decision:'approve'|'reject';reason?:string};result:Certificate;mode:'write'};
  'certificates.requestTraining': {input:{certificateId:ID;note:string};result:Certificate;mode:'write'};
  'members.setUnavailability': {input:{membershipId:ID|null;from:string;to:string;type:Unavailability['type'];note?:string};result:Unavailability;mode:'write'};
  'sla.scorecard': {input:{period:Range;contractorOrgId?:ID};result:SlaScorecard;mode:'read'};
  'sla.saveTargets': {input:{planType:Contract['planType'];responseHours:number;arrivalInWindowPercent:number;firstTimeFixPercent:number;effectiveFrom:Instant};result:SlaTargets;mode:'write'};
  'payouts.list': {input:Query;result:Page<PayoutStatement>;mode:'read'};
  'payouts.get': {input:{id:ID};result:PayoutStatement;mode:'read'};
  'payouts.generate': {input:{period:string};result:PayoutStatement[];mode:'write'};
  'payouts.transition': {input:{statementId:ID;action:'approve'|'mark_paid';reason?:string};result:PayoutStatement;mode:'write'};
  'payouts.query': {input:{statementId:ID;lineId:ID;topic:PayoutQuestion['topic'];message:string};result:PayoutStatement;mode:'write'};
  'payouts.resolveQuery': {input:{statementId:ID;queryId:ID;reply:string;adjustmentMinor?:number};result:PayoutStatement;mode:'write'};
  'twoFactor.get': {input:Record<string,never>;result:TwoFactorStatus;mode:'read'};
  'twoFactor.enable': {input:{code:string};result:TwoFactorStatus & {recoveryCodes:string[]};mode:'write'};
  'twoFactor.disable': {input:{code:string};result:TwoFactorStatus;mode:'write'};
  'jobs.rate': {input:{jobId:ID;stars:JobRating['stars'];tags:string[];comment?:string};result:MaintenanceJob;mode:'write'};
  'jobs.reportProblem': {input:{jobId:ID;reasonCode:'same_problem'|'new_damage'|'not_completed'|'other';details:string;photos:BlobInput[];preferredSlot:Slot|null};result:MaintenanceJob;mode:'write'};
  'jobs.classifyFollowUp': {input:{jobId:ID;classification:'rework'|'new_request';reason:string};result:MaintenanceJob;mode:'write'};
  'filterCare.list': {input:Query;result:Page<FilterCareStatus>;mode:'read'};
  'filterCare.markCleaned': {input:{unitId:ID};result:FilterCareStatus;mode:'write'};
  'filterCare.saveSettings': {input:{thresholdHours:number|null;fallbackDays:number;recipients:FilterCareSettings['recipients'];channels:Channel[]};result:FilterCareSettings;mode:'write'};
  'energy.exportReport': {input:{month:string;propertyIds:ID[];sections:('energy_cost'|'month_comparison'|'co2_offsets'|'alerts_maintenance')[];format:'pdf'|'csv'};result:ReportFile;mode:'read'};
  'units.resolveQr': {input:{code:string};result:QrResolution;mode:'read'};
  'jobs.checkIn': {input:{jobId:ID;method:'location_qr'|'manual';distanceMeters:number|null;qrUnitId:ID|null;reason?:string};result:MaintenanceJob;mode:'write'};
  'jobs.pauseWork': {input:{jobId:ID;paused:boolean};result:MaintenanceJob;mode:'write'};
  'reports.signOff': {input:{jobId:ID;reportId:ID;reportVersion:number;signerName:string;signature:BlobInput|null;absentReason?:string;sitePhoto?:BlobInput};result:WorkReport;mode:'write'};
  'parts.list': {input:Query;result:Page<PartCatalogItem>;mode:'read'};
  'writes.getResult': {input:{operation:string;idempotencyKey:ID};result:WriteResult;mode:'read'};
};
export type OperationName = keyof OperationContracts;
export type RepositoryCall = <K extends OperationName>(operation:K,context:Context|null,input:OperationContracts[K]['input'],options:OperationContracts[K]['mode'] extends 'write' ? WriteOptions : {signal?:AbortSignal})=>Promise<ServiceResult<OperationContracts[K]['result']>>;

/** Subscription is synchronous and is not a Promise Repository operation. */
/** IR71: fixed entity types; cursor_only carries no resource data. */
export type ChangeEntityType = 'unit'|'device'|'measurement'|'allergen_observation'|'command'|'diagnostic_run'|'device_operation'|'alert'|'notification'|'job'|'report'|'attachment'|'offer'|'assignment'|'plan'|'contract'|'invoice'|'payment'|'restriction'|'inquiry'|'automation'|'policy'|'consent'|'membership'|'organization'|'customer'|'property'|'space'|'capability'|'baseline'|'factor'|'mrv_report'|'offset_record'|'client_user'|'ventilation_log'|'unit_import'|'firmware_campaign'|'contractor'|'rate_card'|'certificate'|'unavailability'|'sla_target'|'payout_statement'|'filter_care'|'default_rule_setting'|'session'|'cursor_only';
export type ChangeEvent = {generation:number;cursor:number;eventId:ID;entityType:ChangeEntityType;entityId:ID|null;version:number|null;occurredAt:Instant;changedFields:string[]};
export type Subscribe = (context:Context,input:{afterCursor:number;resources:Exclude<ChangeEntityType,'cursor_only'>[];unitIds:ID[]},listener:(event:ChangeEvent)=>void)=>()=>void;
export type AllergenObservation = {availability:'not_measured'|'unsupported'|'available';substance:string|null;value:number|null;unit:string|null;sourceLabel:string|null;observedAt:Instant|null;evidenceText:string|null};
export type AirSeries = Page<Measurement> & {allergenObservation:AllergenObservation|null};

export type NotificationRecipient = {id:ID;role:Role;displayLabel:string;allowedChannels:Channel[]};
