// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package assets

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// CustomerPage is paging.Page[Customer].
type CustomerPage struct {
	Items           []Customer `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Customer](CustomerPage{})

// PropertyPage is paging.Page[Property].
type PropertyPage struct {
	Items           []Property `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Property](PropertyPage{})

// SpacePage is paging.Page[Space].
type SpacePage struct {
	Items           []Space `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Space](SpacePage{})

// UnitCoveragePage is paging.Page[UnitCoverage].
type UnitCoveragePage struct {
	Items           []UnitCoverage `json:"items"`
	NextCursor      *string        `json:"nextCursor"`
	Total           int            `json:"total"`
	SnapshotVersion int            `json:"snapshotVersion"`
}

var _ = paging.Page[UnitCoverage](UnitCoveragePage{})

// UnitPage is paging.Page[Unit].
type UnitPage struct {
	Items           []Unit  `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Unit](UnitPage{})
