// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Documentation stubs of the further REST routes of this package's operations (IR222): swag documents one
// route per function, so the update route of a save and the verb routes of a transition are annotated here; the
// handlers carry the first route of each operation.

package assets

import (
	"github.com/pradita/ac-project/service/api/internal/ops"
	"github.com/pradita/ac-project/service/api/internal/platform/apperr"
)

var (
	_ ops.Envelope
	_ apperr.DomainError
	_ = swaggerCustomersSaveUpdate
	_ = swaggerPropertiesSaveUpdate
	_ = swaggerSpacesSaveUpdate
	_ = swaggerUnitsSaveUpdate
)

// swaggerCustomersSaveUpdate documents a further REST route.
//
//	@Summary		customers.save (write) — update
//	@ID				customers.save.update
//	@Description	Authorization: admin:asset.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A02
//	@Tags			customers
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target customers, read customers.list)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		CustomerSave	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Customer}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/customers/{id} [put]
func swaggerCustomersSaveUpdate() {}

// swaggerPropertiesSaveUpdate documents a further REST route.
//
//	@Summary		properties.save (write) — update
//	@ID				properties.save.update
//	@Description	Authorization: admin:asset.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A02
//	@Tags			properties
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target properties, read properties.list)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		PropertySave	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Property}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/properties/{id} [put]
func swaggerPropertiesSaveUpdate() {}

// swaggerSpacesSaveUpdate documents a further REST route.
//
//	@Summary		spaces.save (write) — update
//	@ID				spaces.save.update
//	@Description	Authorization: admin:asset.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A02
//	@Tags			spaces
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string		true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer		true	"id present: required (target spaces, read spaces.list)"
//	@Param			id					path		string		true	"input field id"
//	@Param			request				body		SpaceSave	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Space}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/spaces/{id} [put]
func swaggerSpacesSaveUpdate() {}

// swaggerUnitsSaveUpdate documents a further REST route.
//
//	@Summary		units.save (write) — update
//	@ID				units.save.update
//	@Description	Authorization: admin:asset.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR62 spaceId=null is property root; IR74 no tenantId input
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A02
//	@Tags			units
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string		true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer		true	"id present: required (target units, read units.list)"
//	@Param			id					path		string		true	"input field id"
//	@Param			request				body		UnitSave	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Unit}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/units/{id} [put]
func swaggerUnitsSaveUpdate() {}
