// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Documentation stubs of the further REST routes of this package's operations (IR222): swag documents one
// route per function, so the update route of a save and the verb routes of a transition are annotated here; the
// handlers carry the first route of each operation.

package monitoring

import (
	"github.com/pradita/ac-project/service/api/internal/ops"
	"github.com/pradita/ac-project/service/api/internal/platform/apperr"
)

var (
	_ ops.Envelope
	_ apperr.DomainError
	_ = swaggerPoliciesSaveUpdate
)

// swaggerPoliciesSaveUpdate documents a further REST route.
//
//	@Summary		policies.save (write) — update
//	@ID				policies.save.update
//	@Description	Authorization: client:self-customer:kind=alert | admin:alert.policy.write:kind=alert-or-default_alert | admin:automation.policy.write:kind=automation
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR120 default_alert limits HQ-only
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A05, DD-A11, DD-A12, DD-C15
//	@Tags			policies
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string		true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer		true	"id present: required (target policies, read policies.get)"
//	@Param			id					path		string		true	"input field id"
//	@Param			request				body		SaveInput	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Policy}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/policies/{id} [put]
func swaggerPoliciesSaveUpdate() {}
