// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package monitoring

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// AlertPage is paging.Page[Alert].
type AlertPage struct {
	Items           []Alert `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Alert](AlertPage{})

// EvidenceCandidatePage is paging.Page[EvidenceCandidate].
type EvidenceCandidatePage struct {
	Items           []EvidenceCandidate `json:"items"`
	NextCursor      *string             `json:"nextCursor"`
	Total           int                 `json:"total"`
	SnapshotVersion int                 `json:"snapshotVersion"`
}

var _ = paging.Page[EvidenceCandidate](EvidenceCandidatePage{})

// PolicyPage is paging.Page[Policy].
type PolicyPage struct {
	Items           []Policy `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Policy](PolicyPage{})

// VentilationLogPage is paging.Page[VentilationLog].
type VentilationLogPage struct {
	Items           []VentilationLog `json:"items"`
	NextCursor      *string          `json:"nextCursor"`
	Total           int              `json:"total"`
	SnapshotVersion int              `json:"snapshotVersion"`
}

var _ = paging.Page[VentilationLog](VentilationLogPage{})
