// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Documentation stubs of the further REST routes of this package's operations (IR222): swag documents one
// route per function, so the update route of a save and the verb routes of a transition are annotated here; the
// handlers carry the first route of each operation.

package devices

import (
	"github.com/pradita/ac-project/service/api/internal/ops"
	"github.com/pradita/ac-project/service/api/internal/platform/apperr"
)

var (
	_ ops.Envelope
	_ apperr.DomainError
	_ = swaggerCapabilitiesSaveUpdate
	_ = swaggerFirmwareCampaignsControlAbort
	_ = swaggerFirmwareCampaignsControlResume
	_ = swaggerFirmwareCampaignsControlRetryDevice
)

// swaggerCapabilitiesSaveUpdate documents a further REST route.
//
//	@Summary		capabilities.save (write) — update
//	@ID				capabilities.save.update
//	@Description	Authorization: admin:device.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A04
//	@Tags			capabilities
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"id present: required (target capabilities, read capabilities.list)"
//	@Param			id					path		string			true	"input field id"
//	@Param			request				body		CapabilitySave	true	"input; the path parameters come from the route"
//	@Success		200					{object}	ops.Envelope{data=Capability}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/capabilities/{id} [put]
func swaggerCapabilitiesSaveUpdate() {}

// swaggerFirmwareCampaignsControlAbort documents a further REST route.
//
//	@Summary		firmwareCampaigns.control (write) — abort
//	@ID				firmwareCampaigns.control.abort
//	@Description	Authorization: admin:device.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR111 abort requires reason 1–1000; retry_device only for failed or skipped devices
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A20 · This route sets action=abort
//	@Tags			firmwareCampaigns
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"all: required (target firmware_campaign, read firmwareCampaigns.get)"
//	@Param			campaignId			path		string			true	"input field campaignId"
//	@Param			request				body		ControlInput	true	"input; the path parameters and the fixed field come from the route"
//	@Success		200					{object}	ops.Envelope{data=Campaign}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/firmware-campaigns/{campaignId}/abort [post]
func swaggerFirmwareCampaignsControlAbort() {}

// swaggerFirmwareCampaignsControlResume documents a further REST route.
//
//	@Summary		firmwareCampaigns.control (write) — resume
//	@ID				firmwareCampaigns.control.resume
//	@Description	Authorization: admin:device.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR111 abort requires reason 1–1000; retry_device only for failed or skipped devices
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A20 · This route sets action=resume
//	@Tags			firmwareCampaigns
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"all: required (target firmware_campaign, read firmwareCampaigns.get)"
//	@Param			campaignId			path		string			true	"input field campaignId"
//	@Param			request				body		ControlInput	true	"input; the path parameters and the fixed field come from the route"
//	@Success		200					{object}	ops.Envelope{data=Campaign}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/firmware-campaigns/{campaignId}/resume [post]
func swaggerFirmwareCampaignsControlResume() {}

// swaggerFirmwareCampaignsControlRetryDevice documents a further REST route.
//
//	@Summary		firmwareCampaigns.control (write) — retry device
//	@ID				firmwareCampaigns.control.retry_device
//	@Description	Authorization: admin:device.write
//	@Description	Validation: D01; input constraints in the corresponding DD; expectedVersion required for updates; IR111 abort requires reason 1–1000; retry_device only for failed or skipped devices
//	@Description	Recovery: D04: call writes.getResult with the key, then retry the same intent
//	@Description	Design: DD-A20 · This route sets action=retry_device
//	@Tags			firmwareCampaigns
//	@Accept			json
//	@Produce		json
//	@Param			Idempotency-Key		header		string			true	"D04: the same key replays the stored response; another body for the same key is CONFLICT"
//	@Param			X-Expected-Version	header		integer			true	"all: required (target firmware_campaign, read firmwareCampaigns.get)"
//	@Param			campaignId			path		string			true	"input field campaignId"
//	@Param			deviceId			path		string			true	"input field deviceId"
//	@Param			request				body		ControlInput	true	"input; the path parameters and the fixed field come from the route"
//	@Success		200					{object}	ops.Envelope{data=Campaign}
//	@Failure		401					{object}	apperr.DomainError	"UNAUTHENTICATED"
//	@Failure		403					{object}	apperr.DomainError	"FORBIDDEN"
//	@Failure		404					{object}	apperr.DomainError	"NOT_FOUND"
//	@Failure		409					{object}	apperr.DomainError	"CONFLICT / OFFLINE"
//	@Failure		422					{object}	apperr.DomainError	"VALIDATION (fieldErrors)"
//	@Failure		429					{object}	apperr.DomainError	"RATE_LIMITED (retryAfterSeconds)"
//	@Failure		503					{object}	apperr.DomainError	"UNAVAILABLE"
//	@Failure		504					{object}	apperr.DomainError	"TIMEOUT"
//	@Security		BearerAuth
//	@Router			/v1/firmware-campaigns/{campaignId}/devices/{deviceId}/retry [post]
func swaggerFirmwareCampaignsControlRetryDevice() {}
