// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package devices

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// CalibrationRecordPage is paging.Page[CalibrationRecord].
type CalibrationRecordPage struct {
	Items           []CalibrationRecord `json:"items"`
	NextCursor      *string             `json:"nextCursor"`
	Total           int                 `json:"total"`
	SnapshotVersion int                 `json:"snapshotVersion"`
}

var _ = paging.Page[CalibrationRecord](CalibrationRecordPage{})

// CampaignPage is paging.Page[Campaign].
type CampaignPage struct {
	Items           []Campaign `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Campaign](CampaignPage{})

// CapabilityPage is paging.Page[Capability].
type CapabilityPage struct {
	Items           []Capability `json:"items"`
	NextCursor      *string      `json:"nextCursor"`
	Total           int          `json:"total"`
	SnapshotVersion int          `json:"snapshotVersion"`
}

var _ = paging.Page[Capability](CapabilityPage{})

// DeviceEventPage is paging.Page[DeviceEvent].
type DeviceEventPage struct {
	Items           []DeviceEvent `json:"items"`
	NextCursor      *string       `json:"nextCursor"`
	Total           int           `json:"total"`
	SnapshotVersion int           `json:"snapshotVersion"`
}

var _ = paging.Page[DeviceEvent](DeviceEventPage{})

// DeviceOperationPage is paging.Page[DeviceOperation].
type DeviceOperationPage struct {
	Items           []DeviceOperation `json:"items"`
	NextCursor      *string           `json:"nextCursor"`
	Total           int               `json:"total"`
	SnapshotVersion int               `json:"snapshotVersion"`
}

var _ = paging.Page[DeviceOperation](DeviceOperationPage{})

// DevicePage is paging.Page[Device].
type DevicePage struct {
	Items           []Device `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Device](DevicePage{})
