// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package control

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// AutomationPage is paging.Page[Automation].
type AutomationPage struct {
	Items           []Automation `json:"items"`
	NextCursor      *string      `json:"nextCursor"`
	Total           int          `json:"total"`
	SnapshotVersion int          `json:"snapshotVersion"`
}

var _ = paging.Page[Automation](AutomationPage{})

// CommandPage is paging.Page[Command].
type CommandPage struct {
	Items           []Command `json:"items"`
	NextCursor      *string   `json:"nextCursor"`
	Total           int       `json:"total"`
	SnapshotVersion int       `json:"snapshotVersion"`
}

var _ = paging.Page[Command](CommandPage{})

// RunPage is paging.Page[Run].
type RunPage struct {
	Items           []Run   `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[Run](RunPage{})
