// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package billing

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// ContractPage is paging.Page[Contract].
type ContractPage struct {
	Items           []Contract `json:"items"`
	NextCursor      *string    `json:"nextCursor"`
	Total           int        `json:"total"`
	SnapshotVersion int        `json:"snapshotVersion"`
}

var _ = paging.Page[Contract](ContractPage{})

// InquiryPage is paging.Page[Inquiry].
type InquiryPage struct {
	Items           []Inquiry `json:"items"`
	NextCursor      *string   `json:"nextCursor"`
	Total           int       `json:"total"`
	SnapshotVersion int       `json:"snapshotVersion"`
}

var _ = paging.Page[Inquiry](InquiryPage{})

// InvoicePage is paging.Page[Invoice].
type InvoicePage struct {
	Items           []Invoice `json:"items"`
	NextCursor      *string   `json:"nextCursor"`
	Total           int       `json:"total"`
	SnapshotVersion int       `json:"snapshotVersion"`
}

var _ = paging.Page[Invoice](InvoicePage{})

// StatementPage is paging.Page[Statement].
type StatementPage struct {
	Items           []Statement `json:"items"`
	NextCursor      *string     `json:"nextCursor"`
	Total           int         `json:"total"`
	SnapshotVersion int         `json:"snapshotVersion"`
}

var _ = paging.Page[Statement](StatementPage{})
