// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package notify

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// NotificationPage is paging.Page[Notification].
type NotificationPage struct {
	Items           []Notification `json:"items"`
	NextCursor      *string        `json:"nextCursor"`
	Total           int            `json:"total"`
	SnapshotVersion int            `json:"snapshotVersion"`
}

var _ = paging.Page[Notification](NotificationPage{})

// RecipientPage is paging.Page[Recipient].
type RecipientPage struct {
	Items           []Recipient `json:"items"`
	NextCursor      *string     `json:"nextCursor"`
	Total           int         `json:"total"`
	SnapshotVersion int         `json:"snapshotVersion"`
}

var _ = paging.Page[Recipient](RecipientPage{})
