// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package restrictions

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// RestrictionPage is paging.Page[Restriction].
type RestrictionPage struct {
	Items           []Restriction `json:"items"`
	NextCursor      *string       `json:"nextCursor"`
	Total           int           `json:"total"`
	SnapshotVersion int           `json:"snapshotVersion"`
}

var _ = paging.Page[Restriction](RestrictionPage{})

// anyPage is paging.Page[any].
type anyPage struct {
	Items           []any   `json:"items"`
	NextCursor      *string `json:"nextCursor"`
	Total           int     `json:"total"`
	SnapshotVersion int     `json:"snapshotVersion"`
}

var _ = paging.Page[any](anyPage{})
