// Code generated by scripts/swag_annotate.py; DO NOT EDIT.

// Page types of the list operations for the API description (IR220): swag cannot instantiate paging.Page with a
// type of this package from an annotation, so each list result gets a named page with the same fields; the
// conversions below make the build fail when paging.Page changes.

package identity

import (
	"github.com/pradita/ac-project/service/api/internal/platform/paging"
)

// ClientUserPage is paging.Page[ClientUser].
type ClientUserPage struct {
	Items           []ClientUser `json:"items"`
	NextCursor      *string      `json:"nextCursor"`
	Total           int          `json:"total"`
	SnapshotVersion int          `json:"snapshotVersion"`
}

var _ = paging.Page[ClientUser](ClientUserPage{})

// MemberPage is paging.Page[Member].
type MemberPage struct {
	Items           []Member `json:"items"`
	NextCursor      *string  `json:"nextCursor"`
	Total           int      `json:"total"`
	SnapshotVersion int      `json:"snapshotVersion"`
}

var _ = paging.Page[Member](MemberPage{})

// OrganizationPage is paging.Page[Organization].
type OrganizationPage struct {
	Items           []Organization `json:"items"`
	NextCursor      *string        `json:"nextCursor"`
	Total           int            `json:"total"`
	SnapshotVersion int            `json:"snapshotVersion"`
}

var _ = paging.Page[Organization](OrganizationPage{})
